In [1]:
import torch

In [2]:
t = torch.arange(10)
print(t) 
print(t.shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([10])


### View function 

In [3]:
t.view(2,5) # reshapre the tensor to of size - (2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
t.view(-1,5) 
# -1 will by defaultinfer the first dimension 
# use when you are not sure about any dimension size

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

## Squeeze Operation

In [5]:
x = torch.zeros(5, 1)
print(x)
print(x.shape)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]])
torch.Size([5, 1])


In [6]:
y = x.squeeze(1) # squeeze will remove any dimesnion with a value of 1 
y.shape  # turns a tensor of shape [5, 1] to [5]

torch.Size([5])

### Unsqueeze 

In [7]:
x = torch.zeros(5)
print(x)
print(x.shape)

tensor([0., 0., 0., 0., 0.])
torch.Size([5])


In [8]:
y = x.unsqueeze(1) # unsqueeze will add a dimesion of 1 
print(y.shape) # turns a tensor of shape [5] to [5,1]

torch.Size([5, 1])


## Max Operation

In [9]:
a = torch.randn(4, 4)
a

tensor([[-0.5462,  1.3808,  1.4759,  0.1665],
        [-1.6576, -1.2805,  0.5480, -1.7803],
        [ 0.0969, -1.7333,  1.0639, -0.4660],
        [ 0.3135, -0.4781,  0.3603, -0.6883]])

In [10]:
torch.max(a , 1) # returns max values in the specified dimension along with index
                 # specifying 1 as dimension means we want to do the operation row-wise

torch.return_types.max(
values=tensor([1.4759, 0.5480, 1.0639, 0.3603]),
indices=tensor([2, 2, 2, 2]))

In [11]:
torch.max(a , 1)[0] # to fetch the max values

tensor([1.4759, 0.5480, 1.0639, 0.3603])

In [12]:
torch.max(a , 1)[1] # to fetch the index of the corresponding max values

tensor([2, 2, 2, 2])

## Gather

From Pytorch Documentation- 
Gathers values along an axis specified by dim.

input (Tensor) – the source tensor

dim (python:int) – the axis along which to index

index (LongTensor) – the indices of elements to gather


q_values is an torch tensor of (4,4) shape and action is an Longtensor which has indexes which we want to extract from the q_values

In [13]:
q_values = torch.randn(4, 4)
print(q_values)

tensor([[-0.2644, -0.2460, -1.7992, -1.8586],
        [ 0.3272, -0.9674, -0.2881,  0.0738],
        [ 0.0544,  0.5494, -1.7240, -0.8058],
        [ 1.6687,  0.0767,  0.6696, -1.3802]])


In [14]:
action =torch.LongTensor([0 , 1, 2, 3]) # index must be defined as LongTensor

In [15]:
q_values.shape , action.shape 

# q_values -> 2-dimensional tensor 
# action -> 2-dimensional tensor

(torch.Size([4, 4]), torch.Size([4]))

In [16]:
torch.gather(q_values , 1, action.unsqueeze(1)) # 
# unsqueez is used to take care of the error - Index tensor must have same dimensions as input tensor
# returns the values from q_values using the action as indexes
# 1 – we are fetching the values row-wise

tensor([[-0.2644],
        [-0.9674],
        [-1.7240],
        [-1.3802]])