In [0]:
import numpy as np

In [0]:
def lcs_brute_force(first, second):
    """
    Use brute force to calculate the longest common substring of two strings
    Args:
        first: first string
        second: second string
    Returns:
        the length of the longest common substring
    """
    len_first = len(first)
    len_second = len(second)
    max_lcs = -1
    lcs_start, lcs_end = -1, -1
    # for every possible start in the first string
    for i1 in range(len_first):
        # for every possible end in the first string
        for j1 in range(i1, len_first):
            # for every possible start in the second string
            for i2 in range(len_second):
                # for every possible end in the second string
                for j2 in range(i2, len_second):
                    # start and end position of the current
                    # candidates
                    slice_first = slice(i1, j1)
                    slice_second = slice(i2, j2)
                    # if the strings match and the length is the
                    # highest so far
                    if first[slice_first] == second[slice_second] \
                            and j1 - i1 > max_lcs:
                        # save the lengths
                        max_lcs = j1 - i1
                        lcs_start = i1
                        lcs_end = j1

    print("LCS: ", first[lcs_start: lcs_end])
    return max_lcs



In [22]:
if __name__ == '__main__':
    a = "BBBABDABAA"
    b = "AAAABDABBAABB"
    lcs_brute_force(a, b)


LCS:  ABDAB


In [0]:
def lcs_tabular(first, second):
    """
    Calculates the longest common substring using memoization.
    Args:
        first: the first string
        second: the second string
    Returns:
        the length of the longest common substring.
    """
    # initialize the table using numpy because it's convenient
    table = np.zeros((len(first), len(second)), dtype=int)
    for i in range(len(first)):
        for j in range(len(second)):
            if first[i] == second[j]:
                table[i][j] += 1 + table[i - 1][j - 1]
    print(table)
    return np.max(table)

In [24]:
if __name__ == '__main__':
    a = "BBBABDABAA"
    b = "AAAABDABBAABB"
    lcs_tabular(a, b)

[[0 0 0 0 1 0 0 1 1 0 0 1 1]
 [0 0 0 0 1 0 0 1 2 0 0 1 2]
 [0 0 0 0 1 0 0 1 2 0 0 1 2]
 [3 1 1 1 0 0 1 0 0 3 1 0 0]
 [0 0 0 0 2 0 0 2 1 0 0 2 1]
 [0 0 0 0 0 3 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 4 0 0 1 1 0 0]
 [0 0 0 0 2 0 0 5 1 0 0 2 1]
 [2 1 1 1 0 0 1 0 0 2 1 0 0]
 [1 3 2 2 0 0 1 0 0 1 3 0 0]]
