In [1]:
#import libraries
import random
import numpy as np

In [2]:
# create  function for random population
def original_population(chromosomes, genes):
    #initialize the population with zeroes
    population =  np.zeros((chromosomes, genes))
    #loop through each chromosome
    for i in range(chromosomes):
        #get random no. of ones to be created
        ones = random.randint(0, genes)
        #change zeroes to ones
        population[i, 0:ones] = 1
        #shuffle rows
        np.random.shuffle(population[i])
    return population

In [3]:
# create target solution
def create_target_solution(gene):
    #assume that there is an equal number of ones and zeroes
    counting_ones = int(gene/2)

    # build array with equal no. of ones and zeros
    target = np.zeros(gene)
    target[0:counting_ones] = 1

    # shuffle the array to mix zeroes and ones
    np.random.shuffle(target)

    return target

In [4]:
# calculate the fitness of the population
def fitness_function(target,population):
    #create an array of true/false compared to the reference
    identical_to_target = population == target
    #sum no. of genes that are identical
    fitness_weights = identical_to_target.sum(axis = 1)
    return fitness_weights

In [5]:
# select the best parents
def select_parents(population, weights):
    #identify the parent with the highest weight
    parent1 = population[np.argmax(weights)]
    #replace weight with the minimum number
    weights[np.argmax(weights)] = 0
    #identify the parent with the second highest weight
    parent2 = population[np.argmax(weights)]
    return parent1, parent2

In [6]:
 #define function for cross-over
def crossover_reproduction(parents, population):
    #define parents separately
    parent1 = parents[0]
    parent2 = parents[1]

    #randomly assign a point for cross-over
    p = random.randrange(0, len(population))
    print("Crossover point:", p)

    #create children by joining the parents at the cross-over point
    child1 = np.hstack((parent1[0:p],parent2[p:]))
    child2 = np.hstack((parent2[0:p], parent1[p:]))


    return child1, child2

In [7]:
#create function for random mutations
def mutate_population(population, mutation_probability):
    #create array of random mutations that uses the population
    mutation_array = np.random.random(size = (population.shape))
    #compare elements of the array with the probability and put the results into an array
    mutation_boolean = \
        mutation_array >= mutation_probability
    #convert boolean into binary and store to create a new array for the population
    population[mutation_boolean] = \
    np.logical_not(population[mutation_boolean])
    return population

In [8]:
#population of 5 chromosomes, each having 8 genes
population = original_population(5,8)
target = create_target_solution(8)
weights = fitness_function(target,population)

In [12]:
parents = select_parents(population,weights)
children = crossover_reproduction(parents,population)

Crossover point: 3


In [13]:
# append
population_crossover = np.append(population, children, axis= 0)
print('\nPopulation after the cross-over:\n', population_crossover)


Population after the cross-over:
 [[0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1.]]


In [14]:
mutation_probability = 0.05
new_population = mutate_population(population_crossover,mutation_probability)
print('\nNext generation of the population:\n',new_population)


Next generation of the population:
 [[1. 0. 1. 1. 1. 1. 0. 1.]
 [1. 0. 1. 1. 1. 0. 1. 1.]
 [1. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0. 1. 0. 1.]]
